"""Generates the README images in docs/ using the MCP itself.

    python tools/make_showcase.py

docs/showcase.png  grid of characters on grass (themed + random, all generated by the MCP)
docs/walk.gif      a row of characters walking
docs/hammer.gif    the in-chat preview of a blacksmith hammering (4 directions)
"""
import random
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from PIL import Image  # noqa: E402

from lpc_character_mcp import render, server  # noqa: E402
from lpc_character_mcp.catalog import ITEMS, item_animations  # noqa: E402

DOCS = ROOT / "docs"
F = 64


def H(name):  # head
    return {"id": f"head/heads/{name}"}


def find(suffix):
    """Item id that ends with `suffix` (so the script survives folder reshuffles)."""
    hits = [i for i in ITEMS if i.endswith("/" + suffix) or i == suffix]
    return hits[0] if hits else None


def it(suffix, color=None, variant=None):
    item_id = find(suffix)
    if not item_id:
        return None
    out = {"id": item_id}
    if color:
        out["color"] = color
    if variant:
        out["variant"] = variant
    return out


THEMED = [
    ("male", ["body/body:light", "human/heads_human_male", "torso_armour_plate", "arms_armour", "legs_armour",
              "feet_armour", "hat_helmet_greathelm", "weapon_sword_arming", "shield_crusader"]),
    ("male", ["body/body:taupe", "human/heads_human_male", "beards_beard:ginger", "hair_plain:ginger",
              "torso_armour_leather", "legs_pants:brown", "feet_boots_basic:brown", "hat_helmet_barbarian_viking",
              "weapon_blunt_waraxe", "shield_round"]),
    ("male", ["body/body:light", "human/heads_human_male_elderly", "beards_winter:white",
              "torso_clothes_longsleeve:navy", "cape_solid:navy", "legs_pants:navy", "hat_magic_wizard",
              "weapon_magic_gnarled", "feet_shoes_basic:brown"]),
    ("male", ["body_skeleton", "undead/heads_skeleton", "weapon_polearm_scythe"]),
    ("male", ["body/body:green", "orc/heads_orc_male", "torso_armour_leather", "legs_pants:brown",
              "feet_boots_basic:black", "weapon_blunt_mace", "shield_round"]),
    ("male", ["body/body:bronze", "human/heads_human_male", "torso_armour_legion", "legs_skirts_legion",
              "hat_helmet_legion", "shoulders_legion", "feet_sandals", "weapon_polearm_spear", "shield_scutum"]),
    ("male", ["body/body:light", "human/heads_human_male", "torso_clothes_longsleeve:white", "legs_pantaloons:red",
              "feet_boots_basic:black", "hat_tricorne_captain", "weapon_sword_saber"]),
    ("male", ["body/body:light", "human/heads_human_male", "beards_trimmed:dark_brown", "hair_plain:dark_brown",
              "torso_clothes_longsleeve:maroon", "cape_solid:red", "legs_formal:black", "feet_boots_basic:black",
              "hat_formal_crown"]),
    ("female", ["body/body:light", "human/heads_human_female", "hair_long:blonde", "dress_bodice", "hat_formal_tiara"]),
    ("male", ["body/body:fur_grey", "wolf/heads_wolf_male", "tail_wolf:fur_grey", "legs_pants:brown",
              "weapon_sword_longsword"]),
    ("male", ["body/body:fur_brown", "minotaur/heads_minotaur", "legs_pants:brown", "weapon_polearm_halberd"]),
    ("male", ["body/body:bronze", "human/heads_human_male", "hair_plain:dark_brown", "torso_clothes_longsleeve:white",
              "torso_aprons_overalls", "legs_cuffed:brown", "feet_boots_basic:brown", "tool_hammer"]),
    ("male", ["body/body:green", "reptile/heads_lizard_male", "tail_lizard", "torso_armour_leather",
              "legs_pants:brown", "weapon_polearm_spear"]),
    ("male", ["body/body:white", "undead/heads_vampire", "hair_plain:black", "torso_clothes_longsleeve:black",
              "cape_solid:black", "legs_formal:black", "feet_boots_basic:black"]),
    ("male", ["body/body:green", "goblin/heads_goblin", "legs_shorts:brown", "weapon_sword_dagger"]),
    ("female", ["body/body:light", "human/heads_human_female", "head_ears_elven", "hair_long_straight:platinum",
                "torso_clothes_tunic:forest", "legs_pants:brown", "feet_boots_basic:brown", "weapon_ranged_crossbow"]),
]


def themed_items(parts):
    items = []
    for p in parts:
        name, _, color = p.partition(":")
        if name.startswith(("body/", "human/", "orc/", "wolf/", "minotaur/", "reptile/", "goblin/", "undead/")):
            item = {"id": name} if name.startswith("body/") else H(name)
            if name.startswith(("orc/", "wolf/", "minotaur/", "reptile/", "goblin/", "undead/")):
                item = {"id": next((i for i in ITEMS if i.endswith("/" + name.split("/")[1])), "")}
        else:
            item = it(name)
        if not item or item["id"] not in ITEMS:
            continue
        if color:
            item["color"] = color
        items.append(item)
    return items


WEAPONS = ["weapon_sword_arming", "weapon_sword_longsword", "weapon_sword_saber", "weapon_sword_rapier",
           "weapon_polearm_spear", "weapon_polearm_halberd", "weapon_blunt_mace", "weapon_blunt_flail",
           "weapon_blunt_waraxe", "weapon_magic_crystal", "weapon_magic_simple", "weapon_ranged_crossbow",
           "tool_hammer"]
SHIELDS = ["shield_round", "shield_kite", "shield_crusader", "shield_spartan", "shield_heater_revised_wood"]
HEADGEAR = ["hat_helmet_nasal", "hat_helmet_kettle", "hat_helmet_barbuta", "hat_helmet_horned",
            "hat_helmet_armet", "hat_cap_leather_feather", "hat_magic_celestial", "hat_tricorne", "hat_formal_tophat"]


def random_hero(rng, n):
    body = rng.choice(["male", "female"])
    items = server.random_items(body, random.Random(1000 + n))
    kit = []
    if rng.random() < 0.7:
        kit.append(it(rng.choice(WEAPONS)))
    if rng.random() < 0.35:
        kit.append(it(rng.choice(SHIELDS)))
    if rng.random() < 0.4:
        items = [i for i in items if not i["id"].startswith("headwear/")]
        kit.append(it(rng.choice(HEADGEAR)))
    return body, items + [k for k in kit if k and "walk" in item_animations(k["id"], body)]


def standing(items, body, col=0, direction=2):
    comp = render._compose(items, body, ["walk"])
    if "error" in comp:
        return None
    img = dict((a, i) for a, i, _ in comp["rows"])["walk"]
    return img.crop((col * F, direction * F, (col + 1) * F, (direction + 1) * F))


def grass(w, h, seed=7):
    rng = random.Random(seed)
    img = Image.new("RGBA", (w, h), (74, 138, 52, 255))
    px = img.load()
    for y in range(h):
        for x in range(w):
            r = rng.random()
            if r < 0.10:
                px[x, y] = (62, 120, 44, 255)
            elif r < 0.16:
                px[x, y] = (88, 156, 62, 255)
    for _ in range(w * h // 90):  # tufinhos de grama
        x, y = rng.randrange(1, w - 1), rng.randrange(2, h)
        for dy in range(rng.choice([2, 3])):
            px[x, y - dy] = (104, 176, 70, 255)
    return img


def showcase(cols=8, rows=6):
    rng = random.Random(42)
    people = [(b, themed_items(p)) for b, p in THEMED]
    n = 0
    while len(people) < cols * rows:
        people.append(random_hero(rng, n))
        n += 1
    rng.shuffle(people)
    sheet = grass(cols * F, rows * F)
    for k, (body, items) in enumerate(people[: cols * rows]):
        cell = standing(items, body)
        if cell is not None:
            sheet.alpha_composite(cell, ((k % cols) * F, (k // cols) * F))
    sheet.resize((sheet.width * 2, sheet.height * 2), Image.NEAREST).save(DOCS / "showcase.png")


def walking(count=8):
    rng = random.Random(5)
    people = [(b, themed_items(p)) for b, p in THEMED[:count // 2]]
    n = 100
    while len(people) < count:
        people.append(random_hero(rng, n))
        n += 1
    bg = grass(count * F, F + 8, seed=3)
    frames = []
    for col in range(1, 9):  # ciclo do walk (o quadro 0 é a pose parada)
        frame = bg.copy()
        for k, (body, items) in enumerate(people):
            cell = standing(items, body, col=col)
            if cell is not None:
                frame.alpha_composite(cell, (k * F, 4))
        frames.append(frame.resize((frame.width * 2, frame.height * 2), Image.NEAREST).convert("RGB"))
    frames[0].save(DOCS / "walk.gif", save_all=True, append_images=frames[1:], duration=110, loop=0)


def hammer():
    items = themed_items(THEMED[11][1])
    data = server.preview_character(items, "male", "tool_hammer")[0].data
    (DOCS / "hammer.gif").write_bytes(data)


if __name__ == "__main__":
    DOCS.mkdir(exist_ok=True)
    showcase()
    walking()
    hammer()
    for f in sorted(DOCS.iterdir()):
        print(f.name, f.stat().st_size // 1024, "KB")
